recipes-kernel: Skip kernel version check on kernel templates
Currently, SRCREV is set to AUTOREV, causing mismatch between PV and the kernel
version shown in the makefile (see below to see the bitbake log). The solution
is to comment the lines which defaults SRCREV to AUTOREV, leaving the previous
comment to replace the SRCREVs for real ones once kernel changes are done.

    ERROR: linux-yocto-4.8.12+gitAUTOINC+4fb6f24600_d4148a2064-r0.1
    do_kernel_version_sanity_check: Package Version (4.8.12+gitAUTOINC
    +4fb6f24600_d4148a2064) does not match of kernel being built (4.8.21).
    Please update the PV variable to match the kernel source.
    ERROR: linux-yocto-4.8.12+gitAUTOINC+4fb6f24600_d4148a2064-r0.1
    do_kernel_version_sanity_check: Function failed:
    do_kernel_version_sanity_check (log file is located
    at ../tmp/work/myqemu-poky-linux/linux-yocto/4.8.12+gitAUTOINC+4fb6f24600_d4148a2064-r0.1/temp/log.do_kernel_version_sanity_check.17509)

[YOCTO #11064]

Signed-off-by: Leonardo Sandoval <leonardo.sandoval.gonzalez at linux.intel.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>